name: "centreon-gorgone-centreon-config"
arch: "${ARCH}"
platform: "linux"
version_schema: "none"
version: "${VERSION}"
release: "${RELEASE}${DIST}"
section: "default"
priority: "optional"
maintainer: "Centreon <contact@centreon.com>"
description: |
  Configure Centreon Gorgone for use with Centreon Web
  Commit: @COMMIT_HASH@
vendor: "Centreon"
homepage: "https://www.centreon.com"
license: "Apache-2.0"

contents:
  - src: "./configuration/centreon.yaml"
    dst: "/etc/centreon-gorgone/config.d/30-centreon.yaml"
    type: config|noreplace
    file_info:
      owner: centreon-gorgone
      group: centreon-gorgone
      mode: 0640

  - src: "./configuration/centreon-api.yaml"
    dst: "/etc/centreon-gorgone/config.d/31-centreon-api.yaml"
    type: config|noreplace
    file_info:
      owner: centreon-gorgone
      group: centreon-gorgone
      mode: 0660

  - src: "./configuration/centreon-audit.yaml"
    dst: "/etc/centreon-gorgone/config.d/50-centreon-audit.yaml"
    type: config|noreplace
    file_info:
      owner: centreon-gorgone
      group: centreon-gorgone
      mode: 0640

  - dst: "/var/cache/centreon-gorgone/autodiscovery"
    type: dir
    file_info:
      owner: centreon-gorgone
      group: centreon-gorgone
      mode: 0770

scripts:
  postinstall: ./scripts/centreon-gorgone-centreon-config-postinstall.sh

overrides:
  rpm:
    depends:
      - centreon-gorgone = ${VERSION}-${RELEASE}${DIST}
  deb:
    depends:
      - centreon-gorgone (= ${VERSION}-${RELEASE}${DIST})
    replaces:
      - centreon-gorgone (<< 24.07.0)

deb:
  breaks:
    - centreon-gorgone (<< 24.07.0)

rpm:
  summary: Configure Centreon Gorgone for use with Centreon Web
  signature:
    key_file: ${RPM_SIGNING_KEY_FILE}
    key_id: ${RPM_SIGNING_KEY_ID}
