name: centreon-frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/centreon-frontend.yml'
      - 'centreon-frontend/**'
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/centreon-frontend.yml'
      - 'centreon-frontend/**'
    tags:
      - centreon-frontend-22.04.**

env:
  version: "22.04"

jobs:
  centreon-frontend-test:
    runs-on: [self-hosted, common]

    strategy:
      matrix:
        include:
          - rules: frontend
            image: test-frontend-open-source-bullseye

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Test centreon-frontend
        uses: ./.github/actions/runner-docker
        with:
          script_name: frontend-test-${{ matrix.rules }}
          image_name: ${{ matrix.image }}
          image_version: ${{ env.version }}

      - name: Publish linting report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        if: always()
        with:
          name: centreon-frontend-linting-report
          path: "centreon-frontend/packages/*/checkstyle.xml"

      - name: Publish unit tests report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: centreon-frontend-unit-tests-report
          comment_mode: failures
          junit_files: "centreon-frontend/packages/centreon-ui/junit.xml"
