name: centreon-frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/centreon-frontend.yml'
      - 'centreon-frontend/**'
  push:
    branches:
      - dev-22.04.x
    paths:
      - '.github/workflows/centreon-frontend.yml'
      - 'centreon-frontend/**'
    tags:
      - centreon-frontend-22.04.**

env:
  version: "22.04"

jobs:
  ui-context-lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: centreon-frontend

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: centreon-frontend/packages/ui-context

      - name: Lint
        run: npm run eslint -- -o checkstyle.xml -f checkstyle --quiet
        working-directory: centreon-frontend/packages/ui-context

      - name: Publish report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: centreon-frontend-eslint-report
          path: centreon-frontend/packages/ui-context/checkstyle.xml

  centreon-ui-lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: centreon-frontend

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: centreon-frontend/packages/centreon-ui

      - name: Lint
        run: npm run eslint -- -o checkstyle.xml -f checkstyle --quiet
        working-directory: centreon-frontend/packages/centreon-ui

      - name: Publish report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: centreon-frontend-eslint-report
          path: centreon-frontend/packages/centreon-ui/checkstyle.xml

#  centreon-ui-unit-test:
#    runs-on: ubuntu-22.04

#    steps:
#      - uses: actions/checkout@v3

#      - uses: actions/setup-node@v3
#        with:
#          node-version: 17

#      - run: |
#          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#          sudo apt update
#          sudo apt install -y google-chrome-stable

#      - name: Install dependencies
#        run: npm ci --legacy-peer-deps
#        working-directory: centreon-frontend

#      - name: Install dependencies
#        run: npm ci --legacy-peer-deps
#        working-directory: centreon-frontend/packages/centreon-ui

#      - name: Build Storybook
#        run: npm run build:storybook
#        working-directory: centreon-frontend/packages/centreon-ui

#      - name: Unit test
#        run: npm t -- --silent --reporters=jest-junit
#        working-directory: centreon-frontend/packages/centreon-ui

#      - name: Publish unit tests report
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          check_name: centreon-frontend-unit-tests-report
#          comment_mode: failures
#          junit_files: "centreon-frontend/packages/centreon-ui/junit.xml"