---
name: Create web jira version

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
      - develop
      - MON-21232-add-a-check-to-make-sure-jira-previous-version-and-tag-previous-version-are-the-exact-same-before-creating-jira-version-and-tagging
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon/.github/create-jira-version-web.yml"
      - "centreon/**"
      - "!centreon/packages/**"
  workflow_dispatch:

env:
  module: "web"

jobs:
  release:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          module_name: ${{ env.module }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}