name: Centreon build docker test lighthouse

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/docker-builder-test-lighthouse.yml"
      - "ci/docker/Dockerfile.lighthouse"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/docker-builder-test-lighthouse.yml"
      - "ci/docker/Dockerfile.lighthouse"

env:
  version: "23.04"

jobs:
  create-and-push-docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - project: lighthouse

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry-docker.centreon.com
          username: ${{ secrets.ARTI_USER  }}
          password: ${{ secrets.ARTI_PASSWD }}

      - name: build docker ${{ matrix.project }}
        run: docker build --no-cache . -f ci/docker/Dockerfile.${{ matrix.project }} -t registry-docker.centreon.com/docker-global/${{ matrix.project }}:${{ env.version }}

      - name: push docker ${{ matrix.project }}
        run: docker push registry-docker.centreon.com/docker-global/${{ matrix.project }}:${{ env.version }}
