name: Centreon build docker test lighthouse

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/docker-builder-test-lighthouse.yml'
      - 'ci/docker/Dockerfile.lighthouse'
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/docker-builder-test-lighthouse.yml'
      - 'ci/docker/Dockerfile.lighthouse'

env:
  version: "22.10"

jobs:
  create-and-push-docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - project: lighthouse

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: docker.centreon.com
          username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
          password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

      - name: build docker ${{ matrix.project }}
        run: docker build --no-cache . -f ci/docker/Dockerfile.${{ matrix.project }} -t docker.centreon.com/${{ matrix.project }}:${{ env.version }}

      - name: push docker ${{ matrix.project }}
        run: docker push docker.centreon.com/${{ matrix.project }}:${{ env.version }}
