name: Centreon build docker test lighthouse

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/docker/Dockerfile.lighthouse"
  push:
    branches:
      - dev-22.04.x
    paths:
      - ".github/docker/Dockerfile.lighthouse"

env:
  version: "22.04"

jobs:
  create-and-push-docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - project: lighthouse

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: centreon.jfrog.io/docker
          username: ${{ secrets.AUTOMATION_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: build docker ${{ matrix.project }}
        run: docker build --no-cache . -f .github/docker/Dockerfile.${{ matrix.project }} -t centreon.jfrog.io/docker/${{ matrix.project }}:${{ env.version }}

      - name: push docker ${{ matrix.project }}
        run: docker push centreon.jfrog.io/docker/${{ matrix.project }}:${{ env.version }}
