name: Centreon build docker test and backend

on:  
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/docker-builder-test-backend-open-source.yml'
      - 'ci/docker/Dockerfile.test-backend-open-source-alpine'

env:
  version: "22.10"

jobs:
  create-and-push-docker:
    runs-on: common
    
    strategy:
      
      matrix:
        include:
          - project: test-backend-open-source
            distrib: alpine

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: docker.registry.apps.centreon.com
          username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
          password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

      - name: build docker packaging ${{ matrix.project }} ${{ matrix.distrib }}
        run: docker build --no-cache . -f ci/docker/Dockerfile.${{ matrix.project }}-${{ matrix.distrib }} -t docker.registry.apps.centreon.com/${{ matrix.project }}-${{ matrix.distrib }}:${{ env.version }}

      - name: push docker packaging ${{ matrix.project }} ${{ matrix.distrib }}
        run: docker push docker.registry.apps.centreon.com/${{ matrix.project }}-${{ matrix.distrib }}:${{ env.version }}
