name: Centreon widgets build docker

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/docker-builder-packaging-widgets.yml"
      - "ci/docker/Dockerfile.packaging-widgets-centos7"
      - "ci/docker/Dockerfile.packaging-widgets-alma8"
      - "ci/docker/Dockerfile.packaging-widgets-bullseye"
  pull_request:
    paths:
      - ".github/workflows/docker-builder-packaging-widgets.yml"
      - "ci/docker/Dockerfile.packaging-widgets-centos7"
      - "ci/docker/Dockerfile.packaging-widgets-alma8"
      - "ci/docker/Dockerfile.packaging-widgets-bullseye"

env:
  version: "22.10"

jobs:
  create-and-push-docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - project: widgets
            distrib: centos7
          - project: widgets
            distrib: alma8
          - project: widgets
            distrib: bullseye
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry-registry-docker.centreon.com
          username: ${{ secrets.ARTI_USER  }}
          password: ${{ secrets.ARTI_PASSWD }}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          file: ci/docker/Dockerfile.packaging-${{ matrix.project }}-${{ matrix.distrib }}
          context: .
          pull: true
          push: true
          tags: registry-registry-docker.centreon.com/packaging-${{ matrix.project }}-${{ matrix.distrib }}:${{ env.version }}
