name: Centreon plugin-packs build docker

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/docker-builder-packaging-centreon-plugin-packs.yml'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-centos7'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-alma8'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-bullseye'
  pull_request:
    paths:
      - '.github/workflows/docker-builder-packaging-centreon-plugin-packs.yml'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-centos7'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-alma8'
      - 'ci/docker/Dockerfile.packaging-centreon-plugin-packs-bullseye'

env:
  version: "22.10"

jobs:
  create-and-push-docker:
    runs-on: [self-hosted, common]

    strategy:

      matrix:
        include:
          - project: centreon-plugin-packs
            distrib: centos7
          - project: centreon-plugin-packs
            distrib: alma8
          - project: centreon-plugin-packs
            distrib: bullseye
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: docker.registry.apps.centreon.com
          username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
          password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          file: ci/docker/Dockerfile.packaging-${{ matrix.project }}-${{ matrix.distrib }}
          context: .
          pull: true
          push: true
          tags: docker.registry.apps.centreon.com/packaging-${{ matrix.project }}-${{ matrix.distrib }}:${{ env.version }}
