name: Centreon build docker test behat

on:  
  workflow_dispatch:
  push:
    branches:
      - MON-14946-migrate-behat-tests
    paths:
      - '.github/workflows/docker-builder-test-behat.yml'
      - 'ci/docker/Dockerfile.behat'

env:
  version: "22.10"

jobs:
  create-and-push-docker:
    runs-on: common
    
    strategy:
      matrix:
        include:
          - project: behat

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: docker.registry.apps.centreon.com
          username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
          password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

      - name: build docker ${{ matrix.project }} 
        run: docker build --no-cache . -f ci/docker/Dockerfile.${{ matrix.project }} -t docker.registry.apps.centreon.com/${{ matrix.project }}:${{ env.version }}

      - name: push docker ${{ matrix.project }}
        run: docker push docker.registry.apps.centreon.com/${{ matrix.project }}:${{ env.version }}
