name: Centreon build docker test openid

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/docker/Dockerfile.openid"
      - ".github/docker/configs/openidrealm.json"
  push:
    branches:
      - develop
    paths:
      - ".github/docker/Dockerfile.openid"
      - ".github/docker/configs/openidrealm.json"

env:
  version: "23.04"

jobs:
  create-and-push-docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - project: openid

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: centreon.jfrog.io/docker
          username: ${{ secrets.AUTOMATION_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: build docker ${{ matrix.project }}
        run: |
          ls .github/docker/configs
          docker build --no-cache . -f .github/docker/Dockerfile.${{ matrix.project }} -t centreon.jfrog.io/docker/${{ matrix.project }}:${{ env.version }}

      - name: push docker ${{ matrix.project }}
        run: docker push centreon.jfrog.io/docker/${{ matrix.project }}:${{ env.version }}
