name: centreon-js-config

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/js-config.yml"
      - "centreon/packages/js-config/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/js-config.yml"
      - "centreon/packages/js-config/**"
    tags-ignore:
      - js-config-*

env:
  directory: "centreon/packages/js-config"
  centreon_directory: "centreon"

jobs:
  deliver-npm:
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Update JS config version
        run: |
          git config --local user.email "technique-ci@users.noreply.github.com"
          git config --local user.name "technique-ci"
          git config pull.rebase false
          npm version patch -m "js-config-%s" --legacy-peer-deps
          VERSION=js-config-$(node -p "require('./package.json').version")
          git checkout develop
          git pull origin develop
          git add .
          git commit -m "chore: release ${VERSION}"
          git tag ${VERSION}
        working-directory: ${{ env.directory }}

      - name: Push changes
        run: |
          git -c https.extraHeader="AUTHORIZATION: Basic ${{ secrets.CENTREON_TECHNIQUE_PAT }}" push https://github.com/centreon/centreon develop
        shell: bash
      
      - name: Push changes with tags
        run: |
          git -c https.extraHeader="AUTHORIZATION: Basic ${{ secrets.CENTREON_TECHNIQUE_PAT }}" push https://github.com/centreon/centreon develop --tags
        shell: bash

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.directory }}/package.json
          tag: latest
          access: public
