name: centreon-js-config

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "centreon/packages/js-config/**"
  push:
    branches:
      - dev-21.10.x
    paths:
      - ".github/workflows/js-config.yml"
      - "centreon/packages/js-config/**"
    tags-ignore:
      - js-config-*

env:
  version: "21.10"
  directory: "centreon/packages/js-config"
  centreon_directory: "centreon"

jobs:
  deliver-npm:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/dev-21.10.x'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Update JS config version
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git config pull.rebase false
          npm version patch -m "js-config-%s" --legacy-peer-deps
          VERSION=js-config-$(node -p "require('./package.json').version")
          git pull
          git add .
          git commit -m "chore: release ${VERSION}"
          git tag ${VERSION}
        working-directory: ${{ env.directory }}

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin dev-21.10.x && git push --tags

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.directory }}/package.json
          tag: ${{ github.head_ref || github.ref_name }}
          access: public