name: centreon-js-config

on:
  pull_request:
    types:
      - closed
    paths:
      - ".github/workflows/js-config.yml"
      - "centreon/packages/js-config/**"

env:
  directory: "centreon/packages/js-config"
  centreon_directory: "centreon"
  package: 'js-config'
  base_branch: develop

jobs:
  deliver-npm:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.merged == true && github.base_ref == env.base_branch && !startsWith(github.head_ref, 'MON-update-package-versions') }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: ./.github/actions/npm-publish
        with:
          directory: ${{ env.directory }}
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.package }}

  check-package-version:
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.head_ref, 'MON-update-package-versions') }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: ./.github/actions/check-package-version
        with:
          base_branch: ${{ env.base_branch }}
          directory: ${{ env.directory }}