name: centreon-js-config-merge

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - "centreon/packages/js-config/**"
      - ".github/workflows/js-config-merge.yml"

env:
  directory: "centreon/packages/js-config"
  package: "js-config"
  base_branch: dev-22.04.x

jobs:
  clean-up-npm-beta:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.merged == true && !startsWith(github.head_ref, 'MON-update-package-versions') }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/clean-up-npm-tag
        with:
          package: js-config
          npm_token: ${{ secrets.NPM_TOKEN }}

  deliver-npm-beta:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.merged == true && !startsWith(github.head_ref, 'MON-update-package-versions') }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/npm-publish-package
        with:
          directory: ${{ env.directory }}
          pat: ${{ secrets.CENTREON_TECHNIQUE_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.package }}
          release_type: "stable"
          version: "dev-22.04.x"