---
name: Sync stable and dev version branches

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  main:
    name: Sync Stable Branches
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true
    steps:
      - name: git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Sync Branches
        id: release
        uses: ./.github/actions/sync-branches
        with:
          src_branch: master
          dest_branch: develop
