name: Sync stable and dev version branches

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  main:
    name: Sync Stable Branches
    runs-on: ubuntu-24.04
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.repo.name  == 'centreon'
    steps:
      - name: git checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Sync Branches
        id: release
        uses: ./.github/actions/sync-branches
        with:
          src_branch: master
          dest_branch: develop
