name: centreon-ui-context

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui-context/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui-context/**"
    tags-ignore:
      - ui-context-*

env:
  version: "23.04"
  directory: "centreon/packages/ui-context"
  centreon_directory: "centreon"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.centreon_directory }}

      - name: Lint
        run: pnpm eslint -o checkstyle.xml -f checkstyle
        working-directory: ${{ env.directory }}

      - name: Publish report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: centreon-ui-context-eslint-report
          path: ${{ env.directory }}/checkstyle.xml

  deliver-npm:
    runs-on: ubuntu-22.04
    needs: [lint]
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Update JS config version
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git config pull.rebase false
          npm version patch -m "ui-context-%s" --legacy-peer-deps
          VERSION=ui-context-$(node -p "require('./package.json').version")
          git pull
          git add .
          git commit -m "chore: release ${VERSION}"
          git tag ${VERSION}
        working-directory: ${{ env.directory }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          github_token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          ssh: false
      
      - name: Push changes with tags
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          github_token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          tags: true
          ssh: false

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.directory }}/package.json
          tag: ${{ github.head_ref || github.ref_name }}
          access: public