name: centreon-ui

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui/**"
  push:
    branches:
      - dev-22.04.x
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui/**"
    tags-ignore:
      - ui-*

env:
  version: "22.04"
  directory: "centreon/packages/ui"
  centreon_directory: "centreon"
  github_repository: "centreon/centreon-gha"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.centreon_directory }}

      - name: Lint
        run: pnpm eslint -o checkstyle.xml -f checkstyle
        working-directory: ${{ env.directory }}

      - name: Publish report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: centreon-ui-eslint-report
          path: ${{ env.directory }}/checkstyle.xml

  unit-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install -y google-chrome-stable
      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.directory }}

      - name: Install Centreon dependencies
        run: pnpm install
        working-directory: ${{ env.centreon_directory }}

      - name: Build Storybook
        run: pnpm build:storybook
        working-directory: ${{ env.directory }}

      - name: Unit test
        run: pnpm t -- --silent --reporter=jest-junit
        working-directory: ${{ env.directory }}

      - name: Publish unit tests report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: centreon-frontend-unit-tests-report
          comment_mode: failures
          junit_files: ${{ env.directory }}/junit.xml

  deliver-npm:
    runs-on: ubuntu-22.04
    needs: [lint, unit-test]
    if: github.ref == 'refs/heads/dev-22.04.x'

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Update JS config version
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git config pull.rebase false
          npm version patch -m "js-config-%s" --legacy-peer-deps
          VERSION=ui-$(node -p "require('./package.json').version")
          git pull
          git add .
          git commit -m "chore: release ${VERSION}"
          git tag ${VERSION}
        working-directory: ${{ env.directory }}

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin dev-22.04.x && git push --tags

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.directory }}/package.json
          tag: ${{ github.head_ref || github.ref_name }}
          access: public