name: widget-httploader

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-httploader.yml"
      - "widgets/centreon-widget-httploader/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-httploader.yml"
      - "widgets/centreon-widget-httploader/**"
    tags:
      - centreon-widget-httploader-22.04.**

env:
  version: "22.04"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: httploader
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: httploader
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
