name: widget-live-top10-memory-usage

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-live-top10-memory-usage.yml"
      - "widgets/centreon-widget-live-top10-memory-usage/**"
  push:
    branches:
      - dev-22.04.x
    paths:
      - ".github/workflows/widget-live-top10-memory-usage.yml"
      - "widgets/centreon-widget-live-top10-memory-usage/**"
    tags:
      - centreon-widget-live-top10-memory-usage-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: live-top10-memory-usage
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: live-top10-memory-usage
      major_version: ${{ needs.get-version.outputs.major_version }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}
