name: widget-global-health

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-global-health.yml"
      - "widgets/centreon-widget-global-health/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-global-health.yml"
      - "widgets/centreon-widget-global-health/**"
    tags:
      - centreon-widget-global-health-22.04.**

env:
  version: "22.04"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: global-health
    secrets:
      nexus_username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: global-health
    secrets:
      nexus_username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}
