name: widget-service-monitoring

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "widgets/centreon-widget-service-monitoring/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "widgets/centreon-widget-service-monitoring/**"
    tags:
      - centreon-widget-service-monitoring-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-service-monitoring/service-monitoring/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: service-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      registry_username: ${{ secrets.NEXUS_USERNAME }}
      registry_password: ${{ secrets.NEXUS_PASSWORD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: service-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      stability: ${{ needs.get-version.outputs.stability }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      cloudfront_id: ${{ secrets.CLOUDFRONT_ID }}
      update_repo_path: ${{ secrets.UPDATE_REPO_PATH }}
      yum_repo_address: ${{ secrets.YUM_REPO_ADDRESS }}
      yum_repo_key: ${{ secrets.YUM_REPO_KEY }}
      yum_repo_url: ${{ secrets.YUM_REPO_ADDRESS }}