name: widget-hostgroup-monitoring

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-host-monitoring.yml"
      - "widgets/centreon-widget-host-monitoring/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-host-monitoring.yml"
      - "widgets/centreon-widget-host-monitoring/**"
    tags:
      - centreon-widget-host-monitoring-*

env:
  widget_name: "host-monitoring"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: ${{ env.widget_name }}
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: ${{ env.widget_name }}
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
