name: widget-service-monitoring

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-service-monitoring.yml"
      - "widgets/centreon-widget-service-monitoring/**"
  push:
    branches:
      - dev-22.10.x
    paths:
      - ".github/workflows/centreon-widget-service-monitoring.yml"
      - "widgets/centreon-widget-service-monitoring/**"
    tags:
      - centreon-widget-service-monitoring-22.10.**

env:
  version: "22.10"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: service-monitoring
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: service-monitoring
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
