name: widget-live-top10-cpu-usage

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-live-top10-cpu-usage.yml"
      - "widgets/centreon-widget-live-top10-cpu-usage/**"
  push:
    branches:
      - dev-22.10.x
    paths:
      - ".github/workflows/centreon-widget-live-top10-cpu-usage.yml"
      - "widgets/centreon-widget-live-top10-cpu-usage/**"
    tags:
      - centreon-widget-live-top10-cpu-usage-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: live-top10-cpu-usage
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: live-top10-cpu-usage
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
      stability: ${{ needs.get-version.outputs.stability }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_password: ${{ secrets.NEXUS_PASSWD }}
      cloudfront_id: ${{ secrets.CLOUDFRONT_ID }}
      update_repo_path: ${{ secrets.UPDATE_REPO_PATH }}
      yum_repo_address: ${{ secrets.YUM_REPO_ADDRESS }}
      yum_repo_key: ${{ secrets.YUM_REPO_KEY }}
      yum_repo_url: ${{ secrets.YUM_REPO_ADDRESS }}