name: widget-servicegroup-monitoring

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-servicegroup-monitoring.yml"
      - "widgets/centreon-widget-servicegroup-monitoring/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-servicegroup-monitoring.yml"
      - "widgets/centreon-widget-servicegroup-monitoring/**"
    tags:
      - centreon-widget-servicegroup-monitoring-23.04.**

env:
  version: "23.04"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: servicegroup-monitoring
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: servicegroup-monitoring
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
