name: widget-single-metric

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-single-metric.yml"
      - "widgets/centreon-widget-single-metric/**"
  push:
    branches:
      - dev-22.10.x
    paths:
      - ".github/workflows/centreon-widget-single-metric.yml"
      - "widgets/centreon-widget-single-metric/**"
    tags:
      - centreon-widget-single-metric-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-single-metric/single-metric/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: single-metric
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: single-metric
      major_version: ${{ needs.get-version.outputs.major_version }}
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
