name: widget-engine-status

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-engine-status.yml"
      - "widgets/centreon-widget-engine-status/**"
  push:
    branches:
      - dev-21.10.x
    paths:
      - ".github/workflows/centreon-widget-engine-status.yml"
      - "widgets/centreon-widget-engine-status/**"
    tags:
      - centreon-widget-engine-status-22.04.**

env:
  version: "21.10"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: engine-status
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: engine-status
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
