name: widget-engine-status

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-engine-status.yml"
      - "widgets/centreon-widget-engine-status/**"
  push:
    branches:
      - dev-22.04.x
    paths:
      - ".github/workflows/widget-engine-status.yml"
      - "widgets/centreon-widget-engine-status/**"
    tags:
      - centreon-widget-engine-status-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-engine-status/engine-status/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: engine-status
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: engine-status
      major_version: ${{ needs.get-version.outputs.major_version }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}
