name: widget-graph-monitoring

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "widgets/centreon-widget-graph-monitoring/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "widgets/centreon-widget-graph-monitoring/**"
    tags:
      - centreon-widget-graph-monitoring-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-graph-monitoring/graph-monitoring/configs.xml

  package:
    needs: [get-version]
    if: ${{ needs.get-version.outputs.stability != 'stable' }}

    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: graph-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
      commit_hash: ${{ github.sha }}
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_ID }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: graph-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      stability: ${{ needs.get-version.outputs.stability }}
      environment: ${{ needs.get-version.outputs.environment }}
    secrets:
      artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}

  promote:
    needs: [get-version]
    if: ${{ contains(fromJson('["stable"]'), needs.get-version.outputs.stability) }}
    runs-on: [self-hosted, common]
    strategy:
      matrix:
        distrib: [el8, el9, bullseye]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Promote ${{ matrix.distrib }} to stable
        uses: ./.github/actions/promote-to-stable
        with:
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          module: widget-graph-monitoring
          distrib: ${{ matrix.distrib }}
          major_version: ${{ needs.get-version.outputs.major_version }}
          minor_version: ${{ needs.get-version.outputs.minor_version }}
          stability: ${{ needs.get-version.outputs.stability }}

  check-stable-packages:
    needs: [get-version]
    strategy:
      matrix:
        include:
        - image: 'almalinux:8'
          distrib: el8
        - image: 'almalinux:9'
          distrib: el9
        - image: 'debian:bullseye'
          distrib: bullseye

    uses: ./.github/workflows/check-pkg-availability.yml
    with:
      image: ${{ matrix.image }}
      distrib: ${{ matrix.distrib }}
      module: widget-graph-monitoring
      version: "${{ needs.get-version.outputs.major_version }}.${{ needs.get-version.outputs.minor_version }}"