name: widget-tactical-overview

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-tactical-overview.yml"
      - "widgets/centreon-widget-tactical-overview/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-tactical-overview.yml"
      - "widgets/centreon-widget-tactical-overview/**"
    tags:
      - centreon-widget-tactical-overview-23.04.**

env:
  version: "23.04"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: tactical-overview
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: tactical-overview
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
