name: widget-hostgroup-monitoring

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-hostgroup-monitoring.yml"
      - "widgets/centreon-widget-hostgroup-monitoring/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-hostgroup-monitoring.yml"
      - "widgets/centreon-widget-hostgroup-monitoring/**"
    tags:
      - centreon-widget-hostgroup-monitoring-22.04.**

env:
  version: "22.04"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: hostgroup-monitoring
    secrets:
      nexus_username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: hostgroup-monitoring
    secrets:
      nexus_username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}
