name: widget-hostgroup-monitoring

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "widgets/centreon-widget-hostgroup-monitoring/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "widgets/centreon-widget-hostgroup-monitoring/**"
    tags:
      - centreon-widget-hostgroup-monitoring-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/configs.xml

  veracode-analysis:
    concurrency: ci-${{ github.sha }}
    needs: [get-version]
    #uses: ./.github/workflows/veracode-legacy-analysis.yml
    uses: ./.github/workflows/veracode-analysis.yml
    with:
      module_directory: widgets/centreon-widget-hostgroup-monitoring
      module_name: centreon-widget-hostgroup-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      stability: ${{ needs.get-version.outputs.stability }}
    secrets:
      veracode_api_id: ${{ secrets.VERACODE_API_ID }}
      veracode_api_key: ${{ secrets.VERACODE_API_KEY }}

  package:
    needs: [get-version]
    if: ${{ needs.get-version.outputs.stability != 'stable' }}

    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: hostgroup-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
      commit_hash: ${{ github.sha }}
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_ID }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: hostgroup-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      stability: ${{ needs.get-version.outputs.stability }}
      environment: ${{ needs.get-version.outputs.environment }}
    secrets:
      artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}

  promote:
    needs: [get-version]
    if: ${{ contains(fromJson('["stable"]'), needs.get-version.outputs.stability) }}
    runs-on: [self-hosted, common]
    strategy:
      matrix:
        distrib: [el8, el9, bullseye]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Promote ${{ matrix.distrib }} to stable
        uses: ./.github/actions/promote-to-stable
        with:
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          module: widget-hostgroup-monitoring
          distrib: ${{ matrix.distrib }}
          major_version: ${{ needs.get-version.outputs.major_version }}
          minor_version: ${{ needs.get-version.outputs.minor_version }}
          stability: ${{ needs.get-version.outputs.stability }}
