name: widget-single-metric

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-single-metric.yml"
      - "widgets/centreon-widget-single-metric/**"
  push:
    branches:
      - dev-22.10.x
    paths:
      - ".github/workflows/centreon-widget-single-metric.yml"
      - "widgets/centreon-widget-single-metric/**"
    tags:
      - centreon-widget-single-metric-22.10.**

env:
  version: "22.10"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: single-metric
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: single-metric
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
