name: widget-hostgroup-monitoring

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-host-monitoring.yml"
      - "widgets/centreon-widget-host-monitoring/**"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/centreon-widget-host-monitoring.yml"
      - "widgets/centreon-widget-host-monitoring/**"
    tags:
      - centreon-widget-host-monitoring-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-host-monitoring/host-monitoring/configs.xml

  package:
    needs: [get-version]
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: host-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: host-monitoring
      major_version: ${{ needs.get-version.outputs.major_version }}
    secrets:
      artifactory_username: ${{ secrets.REPOS_USERNAME }}
      artifactory_password: ${{ secrets.REPOS_PASSWORD }}
