name: widget-live-top10-cpu-usage

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/widget-live-top10-cpu-usage.yml"
      - "widgets/centreon-widget-live-top10-cpu-usage/**"
  push:
    branches:
      - dev-22.10.x
    paths:
      - ".github/workflows/centreon-widget-live-top10-cpu-usage.yml"
      - "widgets/centreon-widget-live-top10-cpu-usage/**"
    tags:
      - centreon-widget-live-top10-cpu-usage-22.10.**

env:
  version: "22.10"

jobs:
  package:
    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: live-top10-cpu-usage
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}

  delivery:
    needs: [package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: live-top10-cpu-usage
    secrets:
      nexus_username: ${{ secrets.ARTI_USER }}
      nexus_password: ${{ secrets.ARTI_PASSWD }}
