name: widget-ntopng-listing

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "widgets/centreon-widget-ntopng-listing/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "widgets/centreon-widget-ntopng-listing/**"
    tags:
      - centreon-widget-ntopng-listing-*

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: widgets/centreon-widget-ntopng-listing/ntopng-listing/configs.xml

  package:
    needs: [get-version]
    if: ${{ contains(fromJson('["testing", "unstable"]'), needs.get-version.outputs.stability) }}

    uses: ./.github/workflows/widget-package.yml
    with:
      widget_name: ntopng-listing
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
      commit_hash: ${{ github.sha }}
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_ID }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

  delivery:
    needs: [get-version, package]
    uses: ./.github/workflows/widget-delivery.yml
    with:
      widget_name: ntopng-listing
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      stability: ${{ needs.get-version.outputs.stability }}
    secrets:
      artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}
      cloudfront_id: ${{ secrets.CLOUDFRONT_ID }}
      update_repo_path: ${{ secrets.UPDATE_REPO_PATH }}
      yum_repo_address: ${{ secrets.YUM_REPO_ADDRESS }}
      yum_repo_key: ${{ secrets.YUM_REPO_KEY }}
      yum_repo_url: ${{ secrets.YUM_REPO_ADDRESS }}

  promote:
    needs: [get-version]
    if: ${{ contains(fromJson('["stable"]'), needs.get-version.outputs.stability) }}
    runs-on: [self-hosted, common]
    strategy:
      matrix:
        distrib: [el8, el9, bullseye]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Promote ${{ matrix.distrib }} to stable
        uses: ./.github/actions/promote-to-stable
        with:
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          module: widget-ntopng-listing
          distrib: ${{ matrix.distrib }}
          major_version: ${{ needs.get-version.outputs.major_version }}
          minor_version: ${{ needs.get-version.outputs.minor_version }}
          stability: ${{ needs.get-version.outputs.stability }}


